apiVersion: v1
kind: Service
metadata:
  name: alert-webhook
  labels:
    name: alert-webhook
    namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 31780
  selector:
    app: alert-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-webhook
  namespace: monitoring
  labels:
    app: alert-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-webhook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: alert-webhook
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: alert-webhook
        image: harbor.haas-440.pez.pivotal.io/prometheus/malston/alert-webhook:0.1.0
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"
          - name: GMAIL_FROM
            value: "marktalston@gmail.com"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
        volumeMounts:
          - name: config
            mountPath: /amhook/config
      volumes:
        - name: config
          configMap:
            name: am-webhook-config
